image: node:6.5.0


cache:
  paths:
  - node_modules/

services:
  - mongo:latest
  
stages:
  - test
  - deploy

staging:
  stage: test
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=hvu-dev --api-key=$HEROKU_STAGING_API_KEY

production:
  stage: deploy
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=hvu --api-key=$HEROKU_STAGING_API_KEY
  only:
   - master


review_apps:
  stage: test
  image: ruby:latest
  script:
    - gem install dpl
    - heroku create hvu-dev-$CI_BUILD_REF_SLUG
    - dpl --provider=heroku --app=hvu-dev-$CI_BUILD_REF_SLUG --api-key=$HEROKU_STAGING_API_KEY
  environment:
    name: review/$CI_BUILD_REF_NAME
    url: hvu-dev-$CI_BUILD_REF_SLUG.herokuapp.com
    on_stop: stop_review
  only:
   - branches
  except:
  - master

stop_review:
  stage: test
  variables:
    GIT_STRATEGY: none
  script:
    - heroku apps:destroy --app hvu-dev-$CI_BUILD_REF_SLUG --confirm hvu-dev-$CI_BUILD_REF_SLUG
  when: manual
  environment:
    name: review/$CI_BUILD_REF_NAME
    action: stop
  only:
    - branches
  except:
    - master