image: node:4.2.2

cache:
  paths:
  - node_modules/

services:
  - mongo




all_tests:
  script:
   - node SERVER/server.js
   - DPL --provider = Heroku --app = hvu --api-key = $ HEROKU_STAGING_API_KEY