image: node:4.2.2

services:
  - mongo:latest



all_tests:
  script:
   - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 7F0CEB10
   - apt-get update
   - apt-get install -y mongodb-org
   - node SERVER/server.js