image: node:4.2.2
image: ruby:latest

cache:
  paths:
  - node_modules/

services:
  - mongo




all_tests:
  script:
   - gem install dpl
   - dpl --provider=heroku --app=hvu --api-key=$HEROKU_STAGING_API_KEY

