image: node:4.2.2


cache:
  paths:
  - node_modules/

services:
  - mongo
  

staging:
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=hvu-dev --api-key=$HEROKU_STAGING_API_KEY

production:
  image: ruby:latest
  script:
   - gem install dpl
   - dpl --provider=heroku --app=hvu --api-key=$HEROKU_STAGING_API_KEY
  only:
   - master

